name: Python Linting

on:
  push:
    branches:
      - '**' # Trigger workflow on any push to any branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install flake8
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    # Step 4: Run flake8 to lint the code
    - name: Run flake8
      run: flake8 script.py

